version: '2'
services:
    oauth2authentication-app:
        image: oauth2authentication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://oauth2authentication-mysql:3306/oauth2authentication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    oauth2authentication-mysql:
        extends:
            file: mysql.yml
            service: oauth2authentication-mysql
